# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b3b69256a628e68dd584edbee2d99b03c51f97df77719d052be25e8e6685573ba726135d43b603979eb552c981e1354c22631a42525ea22720fc528f760808

test:
  secret_key_base: 1abce834ee0724c92df8e748713ee5c5812014e3a6ea7cc59cbdd8513990703e2f50013c1e9b2a2a32b9b355c4a2add4f0659a2301f40b05ff48e858cdd057a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
